name: Deploy to cPanel
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to cPanel
        uses: pinkasey/cpanel-deploy-action@main
        with:
          hostname: ${{ secrets.CPANEL_HOST }}
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: ${{ secrets.CPANEL_USER }}
          repository_root: '/home/mdsexper/mds-experts'
          branch: main